server:
  port: 9999
  servlet:
    context-path: /client
logging:
  level:
    org: 
      springframework:
        security: DEBUG

security:
  oauth2:
    client:
      clientId: innovation
      clientSecret: innSecret
      accessTokenUri: http://localhost:8080/oauth/access_token
      userAuthorizationUri: http://localhost:8080/oauth/authorize
      clientAuthenticationScheme: form
