server:
  port: 9999
  servlet:
    context-path: /dynamint
logging:
  level:
    org: 
      springframework:
        security: DEBUG
        web: DEBUG
        data: DEBUG
spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  data:
    rest:
      base-path: api/v1
  profiles:
    active:
    - oracle
    - mw